version: '2'
services:
  api:
    build: .
    environment: 
      NODE_ENV: production
      PORT: 5000
      DEBUG: api:*
      MONGO_HOST: db
      MONGO_DATABASE: mindhypertrophy
      MONGO_PORT: 27017
      APP_SECRET:
      ADMIN_PASSWORD:
    ports:
     - "5000:5000"
    depends_on: 
      - "db"
  db:
    image: "mongo"
    ports:
      - "27017:27017"