version: '2'
services:
  api:
    build: .
    environment: 
      - NODE_ENV: production
      - PORT: 80
      - DEBUG: api:*
      - MONGO_HOST: db
      - MONGO_DATABASE: mindhypertrophy
      - MONGO_PORT: 27017
    ports:
     - "80:80"
    depends_on: 
      - "db"
  db:
    image: "mongo"
    ports:
      - "27017:27017"